# Usage:
#   conda env create -f environment.yml
# TODO: Get Snakemake into the file somehow, otherwise install it seperately
# conda install bioconda::snakemake
name: dash
channels: [conda-forge]
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - plotly
  - dash
  - rich
  - jupyter
  - ipywidgets
  - ruff
  - black
  - mypy
  - xlrd
  - icecream
  - loguru
  - pandera
  - scipy
  - pip:
    - snakemake